#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="./f24/invio-telematico.env"
F24_DIR="./f24"

TOTAL_STAGES=10

banner "Desktop Telematico — primo invio F24"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisito: Java"
say "Desktop Telematico è un'applicazione Java: verifichiamo che ci sia."
if command -v java >/dev/null 2>&1 && java -version 2>&1 | head -1; then
  say "Java trovato: ok."
else
  warn "Java non trovato."
  step "Scarica e installa Temurin JRE (LTS) per macOS, poi rilancia il wizard."
  open_url "https://adoptium.net/temurin/releases/?os=mac"
  pause "Fatto? Premi Invio quando Java è installato."
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Credenziali Fisconline (PIN + password telematica)"
say "Per autenticare e inviare i file, oltre allo SPID servono il codice PIN"
say "e la password dei servizi telematici (sono un'altra cosa rispetto a SPID)."
open_url "https://telematici.agenziaentrate.gov.it"
step "Accedi con SPID."
step "Vai su Profilo utente e cerca la voce sul codice PIN (visualizza o genera)."
step "Se non hai mai impostato la password telematica, generala da lì."
note "Le etichette esatte del menù cambiano spesso: se non trovi la voce,"
note "dilla a Claude com'è fatta la pagina e la individuiamo insieme."
warn "Il PIN non viene salvato da questo wizard: tienilo a portata di mano."
pause "PIN e password recuperati?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Download e installazione di Desktop Telematico"
say "Il pacchetto si scarica dall'area riservata."
open_url "https://telematici.agenziaentrate.gov.it/Main/Desktop.jsp"
step "Scarica la versione per macOS e installala (trascina in Applicazioni)."
step "Se macOS blocca l'apertura: tasto destro sull'app → Apri → Apri."
pause "Installato e avviabile?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Primo avvio: utenza locale"
step "Avvia Desktop Telematico."
step "Alla prima apertura crea l'utenza LOCALE (nome utente + password):"
say  "  protegge solo i dati sul tuo Mac, non c'entra con Fisconline."
ask DT_UTENTE_LOCALE "Che nome utente locale hai creato? (per ricordarlo)"
write_env DT_UTENTE_LOCALE "$DT_UTENTE_LOCALE"
pause "Utenza creata e accesso al Desktop riuscito?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Installazione applicazioni: File Internet + controllo F24"
step "Nel Desktop: sezione Applicazioni → Installa software."
step "Installa 'File Internet' (sei utente Fisconline, non Entratel)."
step "Installa il modulo di controllo per l'F24 (sotto 'Moduli di controllo')."
note "Se vedi anche un modulo di COMPILAZIONE F24, installalo e segnalalo a"
note "Claude: cambia il modo in cui prepariamo il file al passo 7."
pause "Applicazioni installate?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Configurazione File Internet"
step "Apri File Internet e vai nelle impostazioni/parametri."
step "Inserisci le credenziali Fisconline (codice fiscale, PIN, password)."
note "Se chiede di generare un ambiente di sicurezza, segui la procedura"
note "guidata e conserva la password che scegli."
pause "Configurato senza errori?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Preparazione del file F24"
say "Serve il file telematico dell'F24 (tracciato) con la riga:"
say "  codice tributo · mese · anno · importo del proprio F24"
say "Il fac-simile HTML con tutti i dati è in:"
say "  (vedi il fac-simile o i dati del proprio F24)"
step "Se al passo 5 hai trovato il modulo di compilazione F24: compila lì il"
step "modello con quei dati e salva il file in $F24_DIR"
step "Altrimenti: fermati qui e chiedi a Claude di generare il tracciato"
step "dalle specifiche tecniche ufficiali, poi rilancia il wizard."
ask F24_FILE "Percorso del file F24 pronto (vuoto se non ancora):"
[[ -n "${F24_FILE}" ]] && write_env F24_FILE "$F24_FILE"
pause "File pronto?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Controllo del file"
step "In Desktop Telematico: Documenti → Controlla."
step "Seleziona il file F24 e il tipo documento F24, lancia il controllo."
step "Esito atteso: file conforme, 0 errori. Se segnala errori, annotali e"
step "riportali a Claude prima di andare avanti."
pause "Controllo superato senza errori?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Autenticazione e invio"
warn "Da qui in poi si trasmette davvero: l'F24 verrà addebitato"
warn "sull'IBAN indicato nel file alla data di versamento."
if confirm "Procedere con autenticazione e invio?"; then
  step "File Internet → Autentica: seleziona il file controllato."
  step "Poi Documenti → Invia (o direttamente dal sito, sezione Servizi →"
  step "Invio, caricando il file autenticato .ccf)."
  ask PROTOCOLLO_INVIO "Protocollo di trasmissione mostrato a fine invio:"
  write_env PROTOCOLLO_INVIO "$PROTOCOLLO_INVIO"
else
  SKIPPED+=("Invio F24 non eseguito: versare entro la scadenza per altro canale")
  say "Invio saltato: nessun problema, il versamento resta da fare altrove."
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Ricevuta"
say "L'esito arriva di norma entro qualche ora/1 giorno."
step "Area riservata → Ricevute (o File Internet → Ricevute): scarica la"
step "ricevuta dell'invio e la quietanza."
step "Salvala nella cartella f24/ con un nome parlante (AAAA-MM_F24_..._quietanza.pdf)"
note "Va conservata: serve per il 770 e in caso di controlli."
pause "Tutto annotato? (puoi chiudere qui e scaricare la ricevuta domani)"

finish
